/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/forms/request`; params?: Router.UnknownInputParams; } | { pathname: `/forms/request2`; params?: Router.UnknownInputParams; } | { pathname: `/forms/request3`; params?: Router.UnknownInputParams; } | { pathname: `/forms/requestpreview`; params?: Router.UnknownInputParams; } | { pathname: `/home/home`; params?: Router.UnknownInputParams; } | { pathname: `/home/homeworker`; params?: Router.UnknownInputParams; } | { pathname: `/learnmore/learnmore`; params?: Router.UnknownInputParams; } | { pathname: `/login/login`; params?: Router.UnknownInputParams; } | { pathname: `/signas/client`; params?: Router.UnknownInputParams; } | { pathname: `/signas/worker`; params?: Router.UnknownInputParams; } | { pathname: `/signup/signup`; params?: Router.UnknownInputParams; } | { pathname: `/WokerForms/WorkerForms1`; params?: Router.UnknownInputParams; } | { pathname: `/WokerForms/WorkerForms2`; params?: Router.UnknownInputParams; } | { pathname: `/WokerForms/WorkerForms3`; params?: Router.UnknownInputParams; } | { pathname: `/WokerForms/WorkerForms4`; params?: Router.UnknownInputParams; } | { pathname: `/WokerForms/WorkerForms5`; params?: Router.UnknownInputParams; } | { pathname: `/WokerForms/WorkerPreview`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/forms/request`; params?: Router.UnknownOutputParams; } | { pathname: `/forms/request2`; params?: Router.UnknownOutputParams; } | { pathname: `/forms/request3`; params?: Router.UnknownOutputParams; } | { pathname: `/forms/requestpreview`; params?: Router.UnknownOutputParams; } | { pathname: `/home/home`; params?: Router.UnknownOutputParams; } | { pathname: `/home/homeworker`; params?: Router.UnknownOutputParams; } | { pathname: `/learnmore/learnmore`; params?: Router.UnknownOutputParams; } | { pathname: `/login/login`; params?: Router.UnknownOutputParams; } | { pathname: `/signas/client`; params?: Router.UnknownOutputParams; } | { pathname: `/signas/worker`; params?: Router.UnknownOutputParams; } | { pathname: `/signup/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/WokerForms/WorkerForms1`; params?: Router.UnknownOutputParams; } | { pathname: `/WokerForms/WorkerForms2`; params?: Router.UnknownOutputParams; } | { pathname: `/WokerForms/WorkerForms3`; params?: Router.UnknownOutputParams; } | { pathname: `/WokerForms/WorkerForms4`; params?: Router.UnknownOutputParams; } | { pathname: `/WokerForms/WorkerForms5`; params?: Router.UnknownOutputParams; } | { pathname: `/WokerForms/WorkerPreview`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/forms/request${`?${string}` | `#${string}` | ''}` | `/forms/request2${`?${string}` | `#${string}` | ''}` | `/forms/request3${`?${string}` | `#${string}` | ''}` | `/forms/requestpreview${`?${string}` | `#${string}` | ''}` | `/home/home${`?${string}` | `#${string}` | ''}` | `/home/homeworker${`?${string}` | `#${string}` | ''}` | `/learnmore/learnmore${`?${string}` | `#${string}` | ''}` | `/login/login${`?${string}` | `#${string}` | ''}` | `/signas/client${`?${string}` | `#${string}` | ''}` | `/signas/worker${`?${string}` | `#${string}` | ''}` | `/signup/signup${`?${string}` | `#${string}` | ''}` | `/WokerForms/WorkerForms1${`?${string}` | `#${string}` | ''}` | `/WokerForms/WorkerForms2${`?${string}` | `#${string}` | ''}` | `/WokerForms/WorkerForms3${`?${string}` | `#${string}` | ''}` | `/WokerForms/WorkerForms4${`?${string}` | `#${string}` | ''}` | `/WokerForms/WorkerForms5${`?${string}` | `#${string}` | ''}` | `/WokerForms/WorkerPreview${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/forms/request`; params?: Router.UnknownInputParams; } | { pathname: `/forms/request2`; params?: Router.UnknownInputParams; } | { pathname: `/forms/request3`; params?: Router.UnknownInputParams; } | { pathname: `/forms/requestpreview`; params?: Router.UnknownInputParams; } | { pathname: `/home/home`; params?: Router.UnknownInputParams; } | { pathname: `/home/homeworker`; params?: Router.UnknownInputParams; } | { pathname: `/learnmore/learnmore`; params?: Router.UnknownInputParams; } | { pathname: `/login/login`; params?: Router.UnknownInputParams; } | { pathname: `/signas/client`; params?: Router.UnknownInputParams; } | { pathname: `/signas/worker`; params?: Router.UnknownInputParams; } | { pathname: `/signup/signup`; params?: Router.UnknownInputParams; } | { pathname: `/WokerForms/WorkerForms1`; params?: Router.UnknownInputParams; } | { pathname: `/WokerForms/WorkerForms2`; params?: Router.UnknownInputParams; } | { pathname: `/WokerForms/WorkerForms3`; params?: Router.UnknownInputParams; } | { pathname: `/WokerForms/WorkerForms4`; params?: Router.UnknownInputParams; } | { pathname: `/WokerForms/WorkerForms5`; params?: Router.UnknownInputParams; } | { pathname: `/WokerForms/WorkerPreview`; params?: Router.UnknownInputParams; };
    }
  }
}
