/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/client/clientwelcome`; params?: Router.UnknownInputParams; } | { pathname: `/login/login`; params?: Router.UnknownInputParams; } | { pathname: `/login/logintest`; params?: Router.UnknownInputParams; } | { pathname: `/signup/clientsignup`; params?: Router.UnknownInputParams; } | { pathname: `/signup/clientsignuptest`; params?: Router.UnknownInputParams; } | { pathname: `/signup/roles`; params?: Router.UnknownInputParams; } | { pathname: `/signup/workersignup`; params?: Router.UnknownInputParams; } | { pathname: `/signup/workersignuptest`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/client/clientwelcome`; params?: Router.UnknownOutputParams; } | { pathname: `/login/login`; params?: Router.UnknownOutputParams; } | { pathname: `/login/logintest`; params?: Router.UnknownOutputParams; } | { pathname: `/signup/clientsignup`; params?: Router.UnknownOutputParams; } | { pathname: `/signup/clientsignuptest`; params?: Router.UnknownOutputParams; } | { pathname: `/signup/roles`; params?: Router.UnknownOutputParams; } | { pathname: `/signup/workersignup`; params?: Router.UnknownOutputParams; } | { pathname: `/signup/workersignuptest`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/client/clientwelcome${`?${string}` | `#${string}` | ''}` | `/login/login${`?${string}` | `#${string}` | ''}` | `/login/logintest${`?${string}` | `#${string}` | ''}` | `/signup/clientsignup${`?${string}` | `#${string}` | ''}` | `/signup/clientsignuptest${`?${string}` | `#${string}` | ''}` | `/signup/roles${`?${string}` | `#${string}` | ''}` | `/signup/workersignup${`?${string}` | `#${string}` | ''}` | `/signup/workersignuptest${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/client/clientwelcome`; params?: Router.UnknownInputParams; } | { pathname: `/login/login`; params?: Router.UnknownInputParams; } | { pathname: `/login/logintest`; params?: Router.UnknownInputParams; } | { pathname: `/signup/clientsignup`; params?: Router.UnknownInputParams; } | { pathname: `/signup/clientsignuptest`; params?: Router.UnknownInputParams; } | { pathname: `/signup/roles`; params?: Router.UnknownInputParams; } | { pathname: `/signup/workersignup`; params?: Router.UnknownInputParams; } | { pathname: `/signup/workersignuptest`; params?: Router.UnknownInputParams; };
    }
  }
}
